
const countryDish = {
"Afghanistan": "Kabuli Palaw",
"Albania": "Tavë kosi",
"Algeria": "Couscous",
"Andorra": "Escudella",
"Angola": "Muamba de galinha",
"Antigua and Barbuda": "Pepperpot",
"Argentina": "Asado",
"Armenia": "Khash",
"Aruba": "Keshi yena",
"Australia": "Vegemite on toast",
"Austria": "Wiener Schnitzel",
"Azerbaijan": "Dolma",
"Bahamas": "Conch",
"Bahrain": "Kabsa",
"Bangladesh": "Rice",
"Barbados": "Cou-Cou",
"Belarus": "Potato pancake",
"Belgium": "Moules-frites",
"Belize": "Boil up",
"Benin": "Kuli-Kuli",
"Bermuda": "Bermuda fish chowder",
"Bhutan": "Ema datshi",
"Bolivia": "Salteñas",
"Bosnia and Herzegovina": "Bosnian pot",
"Botswana": "Seswaa",
"Brazil": "Feijoada",
"Brunei": "Ambuyat",
"Bulgaria": "Banitsa",
"Burkina Faso": "Riz gras",
"Burundi": "Harees",
"Cambodia": "Amok trey",
"Cameroon": "Ndolé",
"Canada": "Poutine",
"Cape Verde": "Cachupa",
"Central African Republic": "Cassava",
"Chad": "Boule",
"Chile": "Empanada",
"China": "Peking Duck",
"Colombia": "Sancocho",
"Comoros": "Langouste a la Vanille",
"Congo": "Moambe chicken",
"Costa Rica": "Gallo pinto",
"Croatia": "Zagorski Štrukli",
"Cuba": "Ropa vieja",
"Cyprus": "Souvla",
"Czech Republic": "Vepřo knedlo zelo",
"Denmark": "Stegt Flæsk",
"Greenland": "Kiviak",
"Djibouti": "Skoudehkaris",
"Dominica": "Mountain chicken",
"Dominican Republic": "Sancocho",
"East Timor": "Ikan Pepes",
"Ecuador": "Encebollado",
"Egypt": "Ful medames",
"El Salvador": "Pupusa",
"Equatorial Guinea": "Succotash",
"Eritrea": "Wat",
"Estonia": "Verivorst",
"Eswatini": "Karoo roast ostrich steak",
"Ethiopia": "Kitfo",
"FAC18": "Salted fish skin",
"Fiji": "Kokoda",
"Finland": "Karjalanpaisti",
"France": "Coq au vin",
"Gabon": "Poulet Nwembye",
"Gambia": "Jollof rice",
"Georgia": "Khachapuri",
"Germany": "Sauerkraut",
"Ghana": "Fufu",
"Gibraltar": "Rosto",
"Greece": "Souvlaki",
"Grenada": "Oil Down",
"Guatemala": "Fiambre",
"Guinea": "Yassa",
"Guinea-Bissau": "Jollof rice",
"Guyana": "Guyana Pepperpot",
"Haiti": "Red beans and rice",
"Honduras": "Baleada",
"Hong Kong": "Crispy fried chicken",
"Hungary": "Goulash",
"Iceland": "Hákarl",
"India": "Khichdi",
"Indonesia": "Rendang",
"Iran": "Abgoosht",
"Iraq": "Masgouf",
"Ireland": "Colcannon",
"Israel": "Meorav Yerushalmi",
"Italy": "Pasta",
"Ivory Coast": "Fufu",
"Jamaica": "Ackee and saltfish",
"Japan": "Sushi",
"Jordan": "Mansaf",
"Kazakhstan": "Beshbarmak",
"Kenya": "Ugali",
"Kiribati": "Laulau",
"North Korea": "Kimchi",
"South Korea": "Kimchi",
"Kosovo": "Flija",
"Kuwait": "Kabsa",
"Kyrgyzstan": "Beshbarmak",
"Laos": "Green papaya salad",
"Latvia": "Potato pancake",
"Lebanon": "Kibbeh",
"Lesotho": "Chakalaka",
"Liberia": "Dumboy",
"Libya": "Bazeen",
"Liechtenstein": "Käsespätzle",
"Lithuania": "Cepelinai",
"Luxembourg": "Judd mat Gaardebounen",
"Macedonia": "Tavče Gravče",
"Madagascar": "Romazava",
"Malawi": "Nshima",
"Malaysia": "Nasi lemak",
"Maldives": "Garudhiya",
"Mali": "Maafe",
"Malta": "Pastizzi",
"Marshall Islands": "Macadamia nut pie",
"Mauritania": "Thieboudienne",
"Mauritius": "Octopus Curry",
"Mexico": "Taco",
"Micronesia": "Bat soup",
"Moldova": "Mămăligă",
"Monaco": "Barbaguian",
"Mongolia": "Buuz",
"Montenegro": "Kačamak",
"Montserrat": "Goat water",
"Morocco": "Couscous",
"Mozambique": "Frango",
"Myanmar": "Mohinga",
"Namibia": "Braai",
"Nauru": "Coconut Crusted Fish",
"Nepal": "Dal bhat",
"Netherlands": "Stamppot",
"New Zealand": "Bacon and egg pie",
"Nicaragua": "Gallo pinto",
"Niger": "Djerma Stew",
"Nigeria": "Fufu",
"Norway": "Fårikål",
"Oman": "Shuwa",
"Pakistan": "Seekh kebab",
"Palau": "Bat soup",
"Panama": "Sancocho",
"Papua New Guinea": "Mumu",
"Paraguay": "Sopa paraguaya",
"Peru": "Ceviche",
"Philippines": "Adobo",
"Poland": "Bigos",
"Qatar": "Kabsa",
"Romania": "Mămăligă",
"Russia": "Pelmeni",
"Rwanda": "Ugali",
"Saint Kitts and Nevis": "Saltfish",
"Saint Lucia": "Green fig and saltfish",
"Saint Vincent and the Grenadines": "Roasted breadfruit",
"Samoa": "Laulau",
"San Marino": "Torta Tre Monti",
"Sao Tome and Principe": "Palm oil stew",
"Saudi Arabia": "Kabsa",
"Senegal": "Thieboudienne",
"Serbia": "Ćevapi",
"Seychelles": "Fruit Bat Soup",
"Sierra Leone": "Cassava",
"Singapore": "Hainanese Chicken Rice",
"Slovakia": "Bryndzové halušky",
"Slovenia": "Ajdovi žganci",
"Solomon Islands": "Poi",
"Somalia": "Injera",
"South Africa": "Bobotie",
"South Sudan": "Kisra",
"Spain": "Tortilla española",
"Sri Lanka": "Rice and curry",
"Sudan": "Ful medames",
"Suriname": "Pom",
"Sweden": "Meatball",
"Switzerland": "Cervelat",
"Syria": "Kibbeh",
"Taiwan": "Beef noodle soup",
"Tajikistan": "Osh pilau",
"Tanzania": "Ugali",
"Thailand": "Pad thai",
"Togo": "Ablo",
"Tonga": "Laulau",
"Trinidad and Tobago": "Callaloo",
"Tobago": "Crab and Dumplings",
"Tunisia": "Couscous",
"Turkey": "Döner",
"Turkmenistan": "Pilaf",
"Tuvalu": "Pulaka",
"Uganda": "Matoke",
"Ukraine": "Borscht",
"United Arab Emirates": "Harees",
"United Kingdom": "Fish and chips",
"United States": "Apple pie",
"Hawaii": "Poke",
"Puerto Rico": "Arroz con gandules",
"United States Virgin Islands": "Fish and cou-cou",
"Uruguay": "Asado",
"Uzbekistan": "Osh",
"Vanuatu": "Lap lap",
"Venezuela": "Pabellón criollo",
"Vietnam": "Phở",
"Yemen": "Kabsa",
"Zambia": "Nshima",
"Zimbabwe": "Sadza"
}
